---
name: Validate on Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  lint_yaml:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Yaml lint
        shell: bash
        run: .github/yamllint.sh
